server:
  servlet:
    context-path: /seller
rpc.manager.url: http://localhost:8081/manager/
rpc:
    client:
        url: http://localhost:8081/manager/
        basePackage: com.xiang.api
spring:
  cache:
    type: hazelcast
  activemq:
    broker-url:
    packages:
      trust-all: true
