spring:
  datasource:
    driver-class-name : com.mysql.cj.jdbc.Driver
    #url : jdbc:mysql://localhost:3306/manager?user=root&password=root&useUnicode=true
    url : jdbc:mysql://localhost:3306/financial?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456

  jpa:
    show-sql: true
  activemq:
    broker-url: tcp://10.5.16.14:61616
  jms:
    pub-sub-domain: true
  server:
    context-path : /manager
    port : 8081

  swagger:
    groupName: manger
    basePackage: com.xiang.manager.controller



